language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install --upgrade setuptools pytest pytest-ordering
  - python setup.py install
# command to run tests
script: py.test surf
